name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    name: Lint
    steps:
      - uses: actions/checkout@v7
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Lint with Rubocop
        run: bundle exec rubocop

  test:
    runs-on: macos-latest
    name: "Test on macOS (Ruby ${{ matrix.ruby-version }})"
    strategy:
      matrix:
        ruby-version:
          - '4.0'
          - '3.4'
          - '3.3'
          - '3.2'
          - '3.1'

    steps:
      - uses: actions/checkout@v7

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rspec
